export enum AdminPermission {
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
  MANAGE_SITES = 'MANAGE_SITES',
  MANAGE_PAGES = 'MANAGE_PAGES',
  MANAGE_PROPERTIES = 'MANAGE_PROPERTIES',
  MANAGE_ROOM_TYPES = 'MANAGE_ROOM_TYPES',
  MANAGE_OWNERS = 'MANAGE_OWNERS',
  MANAGE_API_SETTINGS = 'MANAGE_API_SETTINGS',
  MANAGE_USERS = 'MANAGE_USERS',
}

export const ALL_ADMIN_PERMISSIONS = Object.values(AdminPermission);
