"use client";
import Image from "next/image"; import Link from "next/link"; import { BadgeIndianRupee, Headphones, LockKeyhole, Sparkles } from "lucide-react";
import { Hero } from "@/components/home/Hero"; import { SearchBox } from "@/components/home/SearchBox"; import { HotelCard } from "@/components/hotel/HotelCard"; import { useSite } from "@/components/site/SiteProvider"; import { categories } from "@/data/categories"; import { destinations } from "@/data/destinations"; import { hotels } from "@/data/hotels"; import type { PageSection, PublishedPageConfig } from "@/types/site";
const text=(config:Record<string,unknown>,key:string,fallback:string)=>typeof config[key]==="string"?String(config[key]):fallback; const limit=(config:Record<string,unknown>,fallback:number)=>typeof config.limit==="number"?Math.min(24,Math.max(1,config.limit)):fallback;
function Section({section}:{section:PageSection}){const site=useSite();const city=site.city||site.name;const c=section.config;
  switch(section.type){
    case "hero": return <Hero showSearch={false} sectionConfig={c}/>;
    case "search": return <section className="container page-search-section"><SearchBox/></section>;
    case "property-categories": return <section className="container page-builder-section"><h2>{text(c,"title","Browse by property type")}</h2><p>{text(c,"subtitle",`Find the right stay in ${city}`)}</p><div className="category-grid mt-6">{categories.slice(0,limit(c,8)).map(({name,count,type,icon:Icon})=><Link key={name} href={`/hotels?destination=${encodeURIComponent(city)}&type=${type}`}><Icon/><strong>{name}</strong><span>{count}</span></Link>)}</div></section>;
    case "destinations": return <section className="container page-builder-section"><h2>{text(c,"title","Trending Destinations")}</h2><p>{text(c,"subtitle","Explore places near you")}</p><div className="horizontal-list mt-5">{destinations.slice(0,limit(c,6)).map(d=><Link href={`/hotels?destination=${d.name}`} className="destination-card" key={d.name}><Image src={d.image} alt={d.name} fill className="object-cover" sizes="250px"/><div><b>{d.name}</b><span>{d.count} Properties</span></div></Link>)}</div></section>;
    case "featured-properties": case "popular-hotels": case "popular-villas": case "popular-resorts": case "popular-homestays": return <section className="container page-builder-section"><h2>{text(c,"title","Popular Stays")}</h2><p>{text(c,"subtitle",`Recommended stays in ${city}`)}</p><div className="hotel-list mt-5">{hotels.slice(0,limit(c,8)).map(h=><HotelCard key={h.id} hotel={h}/>)}</div></section>;
    case "why-choose-us": return <section className="container page-builder-section"><div className="benefits"><div><p className="eyebrow">THE {site.name.toUpperCase()} PROMISE</p><h2>{text(c,"title",`Why Book With ${site.name}?`)}</h2></div>{[[BadgeIndianRupee,"Best Price Guarantee"],[Sparkles,"Local Selection"],[LockKeyhole,"Easy & Secure"],[Headphones,"24/7 Support"]].map(([Item,label])=>{const Icon=Item as typeof Sparkles;return <div className="benefit" key={label as string}><Icon/><b>{label as string}</b></div>})}</div></section>;
    case "promotional-banner": case "cta": return <section className="container page-builder-section"><div className="offer-banner"><div className="relative z-10"><h2>{text(c,"title",section.type==="cta"?"Find your next stay":"Exclusive offers")}</h2><p>{text(c,"description",`Discover memorable stays in ${city}`)}</p><Link className="btn-gold mt-5" href={text(c,"buttonLink","/hotels")}>{text(c,"buttonText","Explore stays")}</Link></div></div></section>;
    case "testimonials": case "gallery": case "faq": return <section className="container page-builder-section page-placeholder-section"><h2>{text(c,"title",section.type.replace("-"," "))}</h2><p>{text(c,"subtitle",`${site.name} ${section.type}`)}</p></section>;
    default: return null;
  }
}
export function PageRenderer({page}:{page:PublishedPageConfig}){const sections=[...(page.published.sections||[])].filter(section=>section.enabled).sort((a,b)=>a.order-b.order);return <>{sections.map(section=><Section key={section.id} section={section}/>)}</>}
