"use client";
import { useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, Users } from "lucide-react";
import type { PublicRoom } from "@/types/public-property";
import { publicApiBase } from "@/lib/api-client";

type Availability = { status: string; message?: string; nights?: number; rooms: Array<{ roomId: string; status: string; availableInventory: number; totalRate: number | null }> };
const iso = (date: Date) => date.toISOString().slice(0, 10);
export function AvailabilityPicker({ slug, rooms }: { slug: string; rooms: PublicRoom[] }) {
  const tomorrow = useMemo(() => { const d = new Date(); d.setDate(d.getDate() + 1); return iso(d); }, []);
  const dayAfter = useMemo(() => { const d = new Date(); d.setDate(d.getDate() + 2); return iso(d); }, []);
  const [checkIn, setCheckIn] = useState(tomorrow); const [checkOut, setCheckOut] = useState(dayAfter); const [guests, setGuests] = useState(2); const [result, setResult] = useState<Availability | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function check() { setError(""); if (!checkIn || !checkOut || checkOut <= checkIn) { setError("Check-out must be after check-in."); return; } setBusy(true); try { const response = await fetch(`${publicApiBase}/api/v1/properties/${encodeURIComponent(slug)}/availability?checkIn=${checkIn}&checkOut=${checkOut}&guests=${guests}`); const body = await response.json(); if (!response.ok) throw new Error(Array.isArray(body.message) ? body.message.join(", ") : body.message); setResult(body.data); } catch (reason) { setError(reason instanceof Error ? reason.message : "Availability could not be checked."); } finally { setBusy(false); } }
  return <div className="availability-panel"><div className="availability-title"><div><p>PLAN YOUR STAY</p><h2>Check availability</h2></div><CalendarDays/></div><div className="availability-fields"><label>Check-in<input type="date" min={tomorrow} value={checkIn} onChange={(event) => setCheckIn(event.target.value)}/></label><label>Check-out<input type="date" min={checkIn || tomorrow} value={checkOut} onChange={(event) => setCheckOut(event.target.value)}/></label><label><span><Users/> Guests</span><input type="number" min="1" max="30" value={guests} onChange={(event) => setGuests(Number(event.target.value))}/></label></div><button onClick={check} disabled={busy}>{busy ? "Checking…" : "Check rooms"}</button>{error && <p className="availability-error">{error}</p>}{result?.status === "NOT_CONFIGURED" && <div className="availability-note"><CalendarDays/><div><strong>Online availability is coming soon</strong><p>{result.message} Contact the property before planning your stay.</p></div></div>}{result?.status === "CONFIGURED" && <div className="availability-results">{rooms.map((room, index) => { const roomId = String(room.id || room._id || index); const item = result.rooms.find((entry) => entry.roomId === roomId); return <div key={roomId}><span><CheckCircle2/>{room.name || `Room ${index + 1}`}</span><b>{item?.status === "AVAILABLE" ? `${item.availableInventory} available · ₹${item.totalRate?.toLocaleString("en-IN")}` : item?.status === "UNAVAILABLE" ? "Unavailable" : "Not configured"}</b></div>; })}</div>}</div>;
}
