"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, Eye, EyeOff, LockKeyhole, MessageCircle, Phone, ShieldCheck, UserRound } from "lucide-react";
import { apiRequest } from "@/lib/api-client";
import { Brand } from "@/components/layout/Brand";
export const CUSTOMER_TOKEN = "stayhaven_customer_token";
type Purpose = "register" | "login" | "forgot-password";
type Step = "phone" | "otp" | "profile" | "password-login" | "new-password" | "success";
type Session = { accessToken: string; customer: { name: string } };
type Verify = { mode: string; verificationToken?: string; accessToken?: string; customer?: { name: string } };

export function CustomerAuth() {
  const router = useRouter();
  const [purpose,setPurpose]=useState<Purpose>("login"), [step,setStep]=useState<Step>("phone"), [phone,setPhone]=useState(""), [otp,setOtp]=useState(""), [token,setToken]=useState(""), [busy,setBusy]=useState(false), [error,setError]=useState(""), [show,setShow]=useState(false), [seconds,setSeconds]=useState(0);
  useEffect(()=>{ if(!seconds)return; const timer=setInterval(()=>setSeconds((x)=>Math.max(0,x-1)),1000); return()=>clearInterval(timer); },[seconds]);
  const reset=(next:Purpose)=>{setPurpose(next);setStep("phone");setError("");setOtp("");setToken("")};
  async function requestOtp(){ setBusy(true);setError("");try{await apiRequest("/api/v1/customer/auth/otp/request","",{method:"POST",body:JSON.stringify({phone,purpose})});setStep("otp");setSeconds(60)}catch(e){setError((e as Error).message)}finally{setBusy(false)} }
  async function verifyOtp(){setBusy(true);setError("");try{const response=await apiRequest<{data:Verify}>("/api/v1/customer/auth/otp/verify","",{method:"POST",body:JSON.stringify({phone,purpose,otp})});if(response.data.mode==="session"&&response.data.accessToken){localStorage.setItem(CUSTOMER_TOKEN,response.data.accessToken);router.push("/account");return}setToken(response.data.verificationToken||"");setStep(purpose==="register"?"profile":"new-password")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function complete(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const f=new FormData(event.currentTarget);try{const response=await apiRequest<{data:Session}>("/api/v1/customer/auth/register/complete","",{method:"POST",body:JSON.stringify({verificationToken:token,name:f.get("name"),email:f.get("email")||undefined,password:f.get("password")||undefined,acceptTerms:f.get("terms")==="on"})});localStorage.setItem(CUSTOMER_TOKEN,response.data.accessToken);setStep("success");setTimeout(()=>router.push("/account"),1000)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function passwordLogin(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const f=new FormData(event.currentTarget);try{const response=await apiRequest<{data:Session}>("/api/v1/customer/auth/login","",{method:"POST",body:JSON.stringify({identifier:phone,password:f.get("password")})});localStorage.setItem(CUSTOMER_TOKEN,response.data.accessToken);router.push("/account")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function resetPassword(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const f=new FormData(event.currentTarget);try{await apiRequest("/api/v1/customer/auth/password/reset","",{method:"POST",body:JSON.stringify({resetToken:token,newPassword:f.get("password")})});reset("login");setStep("password-login")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <main className="customer-auth-page"><section className="customer-auth-story"><Link href="/" className="customer-auth-back"><ArrowLeft/> Back to stays</Link><div><p className="market-eyebrow">ONE ACCOUNT. EVERY JOURNEY.</p><h1>Travel beautifully.<br/>Stay meaningfully.</h1><p>Sign in with a secure WhatsApp code. Save favourite stays, manage travellers and keep every booking in one calm place.</p><div className="customer-auth-points"><span>01 <b>WhatsApp-secured access</b></span><span>02 <b>Faster future bookings</b></span><span>03 <b>One profile across every site</b></span></div></div></section><section className="customer-auth-form-wrap"><div className="customer-auth-card"><Brand/>
    <div className="customer-auth-tabs"><button className={purpose==="login"?"active":""} onClick={()=>reset("login")}>Sign in</button><button className={purpose==="register"?"active":""} onClick={()=>reset("register")}>Create account</button></div>
    {step!=="phone"&&step!=="success"&&<button className="auth-inline-back" onClick={()=>setStep(step==="otp"?"phone":"otp")}><ArrowLeft/> Back</button>}
    {step==="phone"&&<><div className="customer-auth-heading"><p>{purpose==="register"?"CREATE YOUR ACCOUNT":"WELCOME BACK"}</p><h2>{purpose==="register"?"Continue with mobile":"Login or create an account"}</h2><span>We will send a six-digit verification code on WhatsApp.</span></div><label className="auth-phone-label">Mobile number<div><span>🇮🇳 +91</span><input inputMode="numeric" value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,"").slice(0,10))} placeholder="Enter mobile number"/></div></label>{error&&<p className="customer-auth-error">{error}</p>}<button className="customer-auth-submit" disabled={busy||phone.length!==10} onClick={requestOtp}>{busy?"Sending…":"Continue with WhatsApp"}</button>{purpose==="login"&&<button className="auth-text-action" onClick={()=>setStep("password-login")}>Login with password</button>}<p className="customer-owner-link">By continuing, you agree to our <Link href="/privacy">Privacy Policy</Link> and Terms.</p></>}
    {step==="otp"&&<><div className="customer-auth-heading"><p>WHATSAPP VERIFICATION</p><h2>Enter verification code</h2><span>We sent the code to +91 {phone}.</span></div><div className="auth-otp-mark"><MessageCircle/><span>Secure WhatsApp OTP</span></div><input className="auth-otp-input" inputMode="numeric" autoFocus value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="• • • • • •"/>{error&&<p className="customer-auth-error">{error}</p>}<button className="customer-auth-submit" disabled={busy||otp.length!==6} onClick={verifyOtp}>{busy?"Verifying…":"Verify & continue"}</button><button className="auth-text-action" disabled={seconds>0||busy} onClick={requestOtp}>{seconds?`Resend code in ${seconds}s`:"Resend code"}</button></>}
    {step==="profile"&&<form onSubmit={complete}><div className="customer-auth-heading"><p>MOBILE VERIFIED</p><h2>Complete your profile</h2><span>Your account is ready. Add your name and an optional password.</span></div><div className="auth-success-line"><CheckCircle2/> WhatsApp number verified</div><label>Full name<div><UserRound/><input name="name" minLength={2} required placeholder="Your full name"/></div></label><label>Email address <small>Optional</small><div><input name="email" type="email" placeholder="you@example.com"/></div></label><label>Create password <small>Optional</small><div><LockKeyhole/><input name="password" type={show?"text":"password"} minLength={8} placeholder="Letter, number & special character"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label><label className="customer-terms"><input type="checkbox" name="terms" required/> I agree to the terms and privacy policy.</label>{error&&<p className="customer-auth-error">{error}</p>}<button className="customer-auth-submit" disabled={busy}>{busy?"Creating account…":"Save and continue"}</button></form>}
    {step==="password-login"&&<form onSubmit={passwordLogin}><div className="customer-auth-heading"><p>PASSWORD LOGIN</p><h2>Login with password</h2><span>Enter your mobile number or email and password.</span></div><label>Mobile number or email<div><Phone/><input value={phone} onChange={e=>setPhone(e.target.value)} required placeholder="Mobile number or email"/></div></label><label>Password<div><LockKeyhole/><input name="password" type={show?"text":"password"} required/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<p className="customer-auth-error">{error}</p>}<button className="customer-auth-submit" disabled={busy}>{busy?"Signing in…":"Login"}</button><button type="button" className="auth-text-action" onClick={()=>reset("forgot-password")}>Forgot password?</button><button type="button" className="auth-text-action" onClick={()=>reset("login")}>Login via WhatsApp OTP</button></form>}
    {step==="new-password"&&<form onSubmit={resetPassword}><div className="customer-auth-heading"><p>SECURE RECOVERY</p><h2>Create new password</h2><span>Use at least 8 characters with a letter, number and special character.</span></div><label>New password<div><LockKeyhole/><input name="password" type={show?"text":"password"} minLength={8} required/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<p className="customer-auth-error">{error}</p>}<button className="customer-auth-submit" disabled={busy}>{busy?"Saving…":"Reset password"}</button></form>}
    {step==="success"&&<div className="auth-created"><CheckCircle2/><h2>Account created successfully</h2><p>Opening your personal travel account…</p></div>}
    <div className="auth-trust"><ShieldCheck/> Your verification code and account details are protected.</div><p className="customer-owner-link">Managing a property? <Link href="/list-your-property">Use the owner portal</Link></p>
  </div></section></main>;
}
