"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, KeyRound, LogOut, ShieldCheck, UserRound } from "lucide-react";
import { apiRequest } from "@/lib/api-client";
import { CUSTOMER_TOKEN } from "./CustomerAuth";
type Customer = { _id?: string; id?: string; name: string; email: string; phone?: string; createdAt?: string };
export function CustomerAccount() {
  const router = useRouter(); const [customer, setCustomer] = useState<Customer | null>(null); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const token = typeof window !== "undefined" ? localStorage.getItem(CUSTOMER_TOKEN) || "" : "";
  useEffect(() => { const current = localStorage.getItem(CUSTOMER_TOKEN) || ""; if (!current) { router.replace("/login"); return; } apiRequest<{ data: Customer }>("/api/v1/customer/me", current).then((value) => setCustomer(value.data)).catch(() => { localStorage.removeItem(CUSTOMER_TOKEN); router.replace("/login"); }); }, [router]);
  async function profile(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { const response = await apiRequest<{ data: Customer }>("/api/v1/customer/me", token, { method: "PATCH", body: JSON.stringify({ name: form.get("name"), phone: form.get("phone") || undefined }) }); setCustomer(response.data); setNotice("Profile updated successfully."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Update failed"); } }
  async function password(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await apiRequest("/api/v1/customer/me/password", token, { method: "PATCH", body: JSON.stringify({ currentPassword: form.get("currentPassword"), newPassword: form.get("newPassword") }) }); event.currentTarget.reset(); setNotice("Password changed successfully."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Password change failed"); } }
  if (!customer) return <div className="account-loading">Preparing your account…</div>;
  return <main className="customer-account"><div className="container"><header><div><p className="market-eyebrow">CUSTOMER ACCOUNT</p><h1>Good to see you, {customer.name.split(" ")[0]}</h1><span>Manage your personal details and account security.</span></div><button onClick={() => { localStorage.removeItem(CUSTOMER_TOKEN); router.push("/"); }}><LogOut/> Sign out</button></header><div className="customer-account-layout"><aside><div className="customer-avatar">{customer.name.charAt(0).toUpperCase()}</div><h2>{customer.name}</h2><p>{customer.email}</p><nav><a href="#profile"><UserRound/> Personal information</a><a href="#security"><KeyRound/> Password & security</a><span><CalendarDays/> Bookings <b>Phase 7</b></span></nav><div className="customer-secure"><ShieldCheck/><p><b>Your account is protected</b>Customer and owner access remain separate.</p></div></aside><div className="customer-account-panels">{(notice || error) && <p className={error ? "account-message error" : "account-message"}>{error || notice}</p>}<section id="profile"><div className="account-panel-heading"><UserRound/><div><p>PROFILE</p><h2>Personal information</h2></div></div><form onSubmit={profile}><label>Full name<input name="name" defaultValue={customer.name} required minLength={2}/></label><label>Email address<input value={customer.email} disabled/><small>Email changes require account verification.</small></label><label>Phone number<input name="phone" defaultValue={customer.phone || ""} placeholder="Add a phone number"/></label><button>Save profile</button></form></section><section id="security"><div className="account-panel-heading"><KeyRound/><div><p>SECURITY</p><h2>Change password</h2></div></div><form onSubmit={password}><label>Current password<input name="currentPassword" type="password" required/></label><label>New password<input name="newPassword" type="password" minLength={8} required/><small>Use at least 8 characters.</small></label><button>Update password</button></form></section></div></div></div></main>;
}
