"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, Eye, EyeOff, LockKeyhole, MessageCircle, ShieldCheck, UserRound, X } from "lucide-react";
import { apiRequest } from "@/lib/api-client";

export const CUSTOMER_TOKEN = "stayhaven_customer_token";
export const CUSTOMER_AUTH_EVENT = "stayhaven-auth-change";
type Purpose = "register" | "login" | "forgot-password";
type Step = "phone" | "otp" | "password" | "profile" | "reset-password" | "success";
type Customer = { name?: string };
type Session = { accessToken: string; customer: Customer };
type Access = { purpose: Purpose; passwordAvailable: boolean };
type Verification = { verificationToken?: string; accessToken?: string; customer?: Customer };

export function CustomerAuthModal({ open, onClose, onAuthenticated }: { open: boolean; onClose: () => void; onAuthenticated?: (customer: Customer) => void }) {
  const [step,setStep]=useState<Step>("phone"),[purpose,setPurpose]=useState<Purpose>("login"),[phone,setPhone]=useState(""),[otp,setOtp]=useState(""),[verificationToken,setVerificationToken]=useState(""),[passwordAvailable,setPasswordAvailable]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[showPassword,setShowPassword]=useState(false),[seconds,setSeconds]=useState(0);
  useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";const close=(event:KeyboardEvent)=>event.key==="Escape"&&onClose();document.addEventListener("keydown",close);return()=>{document.body.style.overflow=previous;document.removeEventListener("keydown",close)}},[open,onClose]);
  useEffect(()=>{if(!seconds)return;const timer=window.setInterval(()=>setSeconds(value=>Math.max(0,value-1)),1000);return()=>window.clearInterval(timer)},[seconds]);
  if(!open)return null;
  const reset=()=>{setStep("phone");setPurpose("login");setPhone("");setOtp("");setVerificationToken("");setPasswordAvailable(false);setError("");setShowPassword(false)};
  const finish=(session:Session)=>{localStorage.setItem(CUSTOMER_TOKEN,session.accessToken);window.dispatchEvent(new Event(CUSTOMER_AUTH_EVENT));onAuthenticated?.(session.customer);setStep("success");window.setTimeout(()=>{onClose();reset()},700)};
  async function requestAccessOtp(){setBusy(true);setError("");try{const response=await apiRequest<{data:Access}>("/api/v1/customer/auth/access/otp","",{method:"POST",body:JSON.stringify({phone})});setPurpose(response.data.purpose);setPasswordAvailable(response.data.passwordAvailable);setOtp("");setStep("otp");setSeconds(60)}catch(caught){setError((caught as Error).message)}finally{setBusy(false)}}
  async function resendOtp(){setBusy(true);setError("");try{await apiRequest("/api/v1/customer/auth/otp/request","",{method:"POST",body:JSON.stringify({phone,purpose})});setSeconds(60)}catch(caught){setError((caught as Error).message)}finally{setBusy(false)}}
  async function verifyOtp(){setBusy(true);setError("");try{const response=await apiRequest<{data:Verification}>("/api/v1/customer/auth/otp/verify","",{method:"POST",body:JSON.stringify({phone,purpose,otp})});if(response.data.accessToken){finish(response.data as Session);return}setVerificationToken(response.data.verificationToken||"");setStep(purpose==="register"?"profile":"reset-password")}catch(caught){setError((caught as Error).message)}finally{setBusy(false)}}
  async function passwordLogin(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setBusy(true);setError("");try{const response=await apiRequest<{data:Session}>("/api/v1/customer/auth/login","",{method:"POST",body:JSON.stringify({identifier:phone,password:data.get("password")})});finish(response.data)}catch(caught){setError((caught as Error).message)}finally{setBusy(false)}}
  async function completeProfile(event?:React.FormEvent<HTMLFormElement>){event?.preventDefault();const data=event?new FormData(event.currentTarget):null;setBusy(true);setError("");try{const response=await apiRequest<{data:Session}>("/api/v1/customer/auth/register/complete","",{method:"POST",body:JSON.stringify({verificationToken,name:data?.get("name")||"Guest",email:data?.get("email")||undefined,password:data?.get("password")||undefined,acceptTerms:true})});finish(response.data)}catch(caught){setError((caught as Error).message)}finally{setBusy(false)}}
  async function startRecovery(){setBusy(true);setError("");try{await apiRequest("/api/v1/customer/auth/otp/request","",{method:"POST",body:JSON.stringify({phone,purpose:"forgot-password"})});setPurpose("forgot-password");setOtp("");setStep("otp");setSeconds(60)}catch(caught){setError((caught as Error).message)}finally{setBusy(false)}}
  async function resetPassword(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setBusy(true);setError("");try{await apiRequest("/api/v1/customer/auth/password/reset","",{method:"POST",body:JSON.stringify({resetToken:verificationToken,newPassword:data.get("password")})});setPurpose("login");setStep("password");setError("")}catch(caught){setError((caught as Error).message)}finally{setBusy(false)}}
  return <div className="customer-auth-overlay" role="presentation" onMouseDown={onClose}><section className="customer-auth-modal" role="dialog" aria-modal="true" aria-labelledby="customer-auth-title" onMouseDown={event=>event.stopPropagation()}><button className="customer-auth-close" onClick={onClose} aria-label="Close login"><X/></button>
    {step!=="phone"&&step!=="success"&&<button className="auth-inline-back" onClick={()=>{setError("");setStep(step==="otp"?"phone":"otp")}}><ArrowLeft/> Back</button>}
    {step==="phone"&&<><div className="customer-auth-heading"><p>ONE ACCOUNT. EVERY STAY.</p><h2 id="customer-auth-title">Login or create an account</h2><span>Enter your mobile number. We will send a secure verification code on WhatsApp.</span></div><label className="auth-phone-label">Mobile number<div><span>🇮🇳 +91</span><input autoFocus inputMode="numeric" autoComplete="tel-national" value={phone} onChange={event=>setPhone(event.target.value.replace(/\D/g,"").slice(0,10))} placeholder="Enter 10-digit mobile number"/></div></label>{error&&<p className="customer-auth-error">{error}</p>}<button className="customer-auth-submit" disabled={busy||phone.length!==10} onClick={requestAccessOtp}>{busy?"Sending code…":"Continue"}</button><p className="customer-auth-terms">By continuing, you agree to our <Link href="/privacy">Privacy Policy</Link> and <Link href="/terms">Terms</Link>.</p></>}
    {step==="otp"&&<><div className="customer-auth-heading"><p>WHATSAPP VERIFICATION</p><h2 id="customer-auth-title">Verify your mobile number</h2><span>Enter the 6-digit code sent to +91 {phone}.</span></div><div className="auth-otp-mark"><MessageCircle/><span>Secure WhatsApp OTP</span></div><input className="auth-otp-input" inputMode="numeric" autoComplete="one-time-code" autoFocus value={otp} onChange={event=>setOtp(event.target.value.replace(/\D/g,"").slice(0,6))} placeholder="••••••" aria-label="Verification code"/>{error&&<p className="customer-auth-error">{error}</p>}<button className="customer-auth-submit" disabled={busy||otp.length!==6} onClick={verifyOtp}>{busy?"Verifying…":purpose==="register"?"Verify & create account":"Verify & login"}</button><button className="auth-text-action" disabled={seconds>0||busy} onClick={resendOtp}>{seconds?`Resend code in ${seconds}s`:"Resend code"}</button>{purpose==="login"&&passwordAvailable&&<button className="auth-password-option" onClick={()=>{setError("");setStep("password")}}><LockKeyhole/> Login with password instead</button>}</>}
    {step==="password"&&<form onSubmit={passwordLogin}><div className="customer-auth-heading"><p>PASSWORD LOGIN</p><h2 id="customer-auth-title">Welcome back</h2><span>Login to the account registered with +91 {phone}.</span></div><label>Password<div><LockKeyhole/><input name="password" type={showPassword?"text":"password"} autoFocus required placeholder="Enter your password"/><button type="button" onClick={()=>setShowPassword(!showPassword)} aria-label="Show password">{showPassword?<EyeOff/>:<Eye/>}</button></div></label>{error&&<p className="customer-auth-error">{error}</p>}<button className="customer-auth-submit" disabled={busy}>{busy?"Signing in…":"Login"}</button><button type="button" className="auth-text-action" onClick={startRecovery}>Forgot password?</button><button type="button" className="auth-text-action" onClick={()=>setStep("otp")}>Login with WhatsApp OTP</button></form>}
    {step==="profile"&&<form onSubmit={completeProfile}><div className="customer-auth-heading"><p>ACCOUNT CREATED</p><h2 id="customer-auth-title">Tell us about yourself</h2><span>These details are optional. You can add or change them later.</span></div><div className="auth-success-line"><CheckCircle2/> Mobile number verified</div><label>Full name <small>Optional</small><div><UserRound/><input name="name" minLength={2} placeholder="Your full name"/></div></label><label>Email address <small>Optional</small><div><input name="email" type="email" placeholder="you@example.com"/></div></label><label>Create password <small>Optional</small><div><LockKeyhole/><input name="password" type={showPassword?"text":"password"} minLength={8} placeholder="Letter, number & special character"/><button type="button" onClick={()=>setShowPassword(!showPassword)} aria-label="Show password">{showPassword?<EyeOff/>:<Eye/>}</button></div></label>{error&&<p className="customer-auth-error">{error}</p>}<button className="customer-auth-submit" disabled={busy}>{busy?"Saving…":"Save & continue"}</button><button type="button" className="auth-skip" disabled={busy} onClick={()=>completeProfile()}>Skip for now</button></form>}
    {step==="reset-password"&&<form onSubmit={resetPassword}><div className="customer-auth-heading"><p>SECURE RECOVERY</p><h2 id="customer-auth-title">Create a new password</h2><span>Use at least 8 characters with a letter, number and special character.</span></div><label>New password<div><LockKeyhole/><input name="password" type={showPassword?"text":"password"} minLength={8} required autoFocus/><button type="button" onClick={()=>setShowPassword(!showPassword)} aria-label="Show password">{showPassword?<EyeOff/>:<Eye/>}</button></div></label>{error&&<p className="customer-auth-error">{error}</p>}<button className="customer-auth-submit" disabled={busy}>{busy?"Saving…":"Reset password"}</button></form>}
    {step==="success"&&<div className="auth-created"><CheckCircle2/><h2 id="customer-auth-title">You’re signed in</h2><p>Your stays and account are ready.</p></div>}{step!=="success"&&<div className="auth-trust"><ShieldCheck/> Your code and account details are securely protected.</div>}
  </section></div>;
}
