"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, Eye, EyeOff, LockKeyhole, Mail, Phone, UserRound } from "lucide-react";
import { apiRequest } from "@/lib/api-client";
import { Brand } from "@/components/layout/Brand";
export const CUSTOMER_TOKEN = "stayhaven_customer_token";
type Session = { data: { accessToken: string; customer: { name: string } } };
export function CustomerAuth() {
  const router = useRouter(); const [mode, setMode] = useState<"login" | "register">("login"); const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget); try { const body = mode === "register" ? { name: form.get("name"), email: form.get("email"), phone: form.get("phone") || undefined, password: form.get("password"), acceptTerms: form.get("terms") === "on" } : { email: form.get("email"), password: form.get("password") }; const response = await apiRequest<Session>(`/api/v1/customer/auth/${mode}`, "", { method: "POST", body: JSON.stringify(body) }); localStorage.setItem(CUSTOMER_TOKEN, response.data.accessToken); router.push("/account"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to continue"); } finally { setBusy(false); } }
  return <main className="customer-auth-page"><section className="customer-auth-story"><Link href="/" className="customer-auth-back"><ArrowLeft/> Back to stays</Link><div><p className="market-eyebrow">YOUR NEXT STORY STARTS HERE</p><h1>Travel beautifully.<br/>Stay meaningfully.</h1><p>Create one customer account for saved stays, future bookings and a smoother journey across every marketplace.</p><div className="customer-auth-points"><span>01 <b>Discover verified stays</b></span><span>02 <b>Keep your profile secure</b></span><span>03 <b>Prepare for effortless booking</b></span></div></div></section><section className="customer-auth-form-wrap"><div className="customer-auth-card"><Brand/><div className="customer-auth-tabs"><button className={mode === "login" ? "active" : ""} onClick={() => setMode("login")}>Sign in</button><button className={mode === "register" ? "active" : ""} onClick={() => setMode("register")}>Create account</button></div><div className="customer-auth-heading"><p>{mode === "login" ? "WELCOME BACK" : "JOIN THE JOURNEY"}</p><h2>{mode === "login" ? "Sign in to your account" : "Create your customer account"}</h2><span>{mode === "login" ? "Access your profile and prepare for future bookings." : "Your owner account remains completely separate."}</span></div><form onSubmit={submit}>{mode === "register" && <label>Full name<div><UserRound/><input name="name" minLength={2} required placeholder="Your full name"/></div></label>}<label>Email address<div><Mail/><input name="email" type="email" required placeholder="you@example.com"/></div></label>{mode === "register" && <label>Phone number <small>Optional</small><div><Phone/><input name="phone" minLength={7} placeholder="Your contact number"/></div></label>}<label>Password<div><LockKeyhole/><input name="password" type={show ? "text" : "password"} minLength={8} required placeholder="Minimum 8 characters"/><button type="button" onClick={() => setShow(!show)} aria-label={show ? "Hide password" : "Show password"}>{show ? <EyeOff/> : <Eye/>}</button></div></label>{mode === "register" && <label className="customer-terms"><input type="checkbox" name="terms" required/> I agree to the terms and privacy policy.</label>}{error && <p className="customer-auth-error">{error}</p>}<button className="customer-auth-submit" disabled={busy}>{busy ? "Please wait…" : mode === "login" ? "Sign in securely" : "Create my account"}</button></form><p className="customer-owner-link">Managing a property? <Link href="/list-your-property">Use the owner portal</Link></p></div></section></main>;
}
