"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, CheckCircle2, Heart, KeyRound, Laptop, LogOut, Plus, ShieldCheck, Trash2, UserRound, Users } from "lucide-react";
import { apiRequest } from "@/lib/api-client";
import { CUSTOMER_TOKEN } from "./CustomerAuth";
type Traveller={id:string;name:string;relation?:string;gender?:string};
type Session={id:string;device:string;createdAt:string;lastActiveAt:string};
type Customer={name:string;email?:string;phone?:string;gender?:string;nationality?:string;city?:string;state?:string;coTravellers?:Traveller[]};
type Booking={_id:string;bookingNumber:string;propertyName:string;checkIn:string;checkOut:string;status:string;grossAmount:number;roomName:string};
type View="profile"|"travellers"|"trips"|"wishlist"|"devices"|"security";
export function CustomerAccount(){
 const router=useRouter(); const [customer,setCustomer]=useState<Customer|null>(null),[view,setView]=useState<View>("profile"),[bookings,setBookings]=useState<Booking[]>([]),[sessions,setSessions]=useState<Session[]>([]),[tripTab,setTripTab]=useState("upcoming"),[notice,setNotice]=useState(""),[error,setError]=useState(""); const token=typeof window!=="undefined"?localStorage.getItem(CUSTOMER_TOKEN)||"":"";
 const load=()=>apiRequest<{data:Customer}>("/api/v1/customer/me",token).then(r=>setCustomer(r.data));
 useEffect(()=>{const current=localStorage.getItem(CUSTOMER_TOKEN)||"";if(!current){router.replace("/login");return}Promise.all([apiRequest<{data:Customer}>("/api/v1/customer/me",current),apiRequest<{data:Booking[]}>("/api/v1/customer/bookings",current),apiRequest<{data:Session[]}>("/api/v1/customer/sessions",current)]).then(([a,b,c])=>{setCustomer(a.data);setBookings(b.data);setSessions(c.data)}).catch(()=>{localStorage.removeItem(CUSTOMER_TOKEN);router.replace("/login")})},[router]);
 const flash=(message:string)=>{setError("");setNotice(message);setTimeout(()=>setNotice(""),3500)};
 async function profile(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await apiRequest("/api/v1/customer/me",token,{method:"PATCH",body:JSON.stringify(Object.fromEntries(f))});await load();flash("Profile updated successfully") }catch(x){setError((x as Error).message)}}
 async function addTraveller(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await apiRequest("/api/v1/customer/co-travellers",token,{method:"POST",body:JSON.stringify(Object.fromEntries(f))});e.currentTarget.reset();await load();flash("Co-traveller added") }catch(x){setError((x as Error).message)}}
 async function removeTraveller(id:string){await apiRequest(`/api/v1/customer/co-travellers/${id}`,token,{method:"DELETE"});await load()}
 async function password(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await apiRequest("/api/v1/customer/me/password",token,{method:"PATCH",body:JSON.stringify(Object.fromEntries(f))});e.currentTarget.reset();flash("Password changed successfully") }catch(x){setError((x as Error).message)}}
 const logout=()=>{localStorage.removeItem(CUSTOMER_TOKEN);router.push("/")};
 if(!customer)return <div className="account-loading">Preparing your account…</div>;
 const filtered=bookings.filter(b=>tripTab==="cancelled"?b.status==="CANCELLED":tripTab==="completed"?new Date(b.checkOut)<new Date()&&b.status!=="CANCELLED":new Date(b.checkOut)>=new Date()&&b.status!=="CANCELLED");
 const nav:[View,string,React.ReactNode][]=[["profile","My profile",<UserRound key="p"/>],["travellers","Co-travellers",<Users key="t"/>],["trips","My trips",<CalendarDays key="b"/>],["wishlist","Wishlist",<Heart key="w"/>],["devices","Logged-in devices",<Laptop key="d"/>],["security","Password & security",<KeyRound key="s"/>]];
 return <main className="customer-account"><div className="account-hero"><div className="container"><div className="customer-avatar">{customer.name[0].toUpperCase()}</div><div><p>WELCOME BACK</p><h1>{customer.name}</h1><span>+{customer.phone}{customer.email?` · ${customer.email}`:""}</span></div></div></div><div className="container customer-account-layout"><aside><p className="account-nav-label">MY ACCOUNT</p><nav>{nav.map(([id,label,icon])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}>{icon}{label}</button>)}<button onClick={logout}><LogOut/>Logout</button></nav><div className="customer-secure"><ShieldCheck/><p><b>Your account is protected</b>WhatsApp-secured customer access.</p></div></aside><div className="customer-account-panels">{(notice||error)&&<p className={error?"account-message error":"account-message"}>{error||notice}</p>}
 {view==="profile"&&<section><div className="account-panel-heading"><UserRound/><div><p>PERSONAL DETAILS</p><h2>My profile</h2></div></div><form onSubmit={profile}><label>Full name<input name="name" defaultValue={customer.name} required/></label><label>Email address<input name="email" type="email" defaultValue={customer.email||""} placeholder="Add email address"/></label><label>Verified mobile<input value={`+${customer.phone}`} disabled/></label><label>Gender<select name="gender" defaultValue={customer.gender||""}><option value="">Select gender</option><option>Female</option><option>Male</option><option>Other</option></select></label><label>Nationality<input name="nationality" defaultValue={customer.nationality||""}/></label><label>City of residence<input name="city" defaultValue={customer.city||""}/></label><label>State<input name="state" defaultValue={customer.state||""}/></label><button>Save profile</button></form></section>}
 {view==="travellers"&&<section><div className="account-panel-heading"><Users/><div><p>TRAVEL COMPANIONS</p><h2>Co-travellers</h2></div></div><form onSubmit={addTraveller}><label>Full name<input name="name" required minLength={2}/></label><label>Relationship<input name="relation" placeholder="Family, friend…"/></label><label>Gender<select name="gender"><option value="">Select</option><option>Female</option><option>Male</option><option>Other</option></select></label><button><Plus/> Add co-traveller</button></form><div className="traveller-list">{customer.coTravellers?.map(x=><article key={x.id}><div className="mini-avatar">{x.name[0]}</div><p><b>{x.name}</b><span>{x.relation||x.gender||"Traveller"}</span></p><button onClick={()=>removeTraveller(x.id)} aria-label="Remove traveller"><Trash2/></button></article>)}{!customer.coTravellers?.length&&<div className="account-empty"><Users/><h3>No co-travellers saved</h3><p>Add traveller details to make future bookings faster.</p></div>}</div></section>}
 {view==="trips"&&<section><div className="account-panel-heading"><CalendarDays/><div><p>YOUR JOURNEYS</p><h2>My trips</h2></div></div><div className="trip-tabs">{["upcoming","cancelled","completed"].map(x=><button className={tripTab===x?"active":""} onClick={()=>setTripTab(x)} key={x}>{x}</button>)}</div><div className="trip-list">{filtered.map(b=><article key={b._id}><div><span>{new Date(b.checkIn).toLocaleDateString("en-IN",{day:"numeric",month:"short"})}</span><small>TO</small><span>{new Date(b.checkOut).toLocaleDateString("en-IN",{day:"numeric",month:"short"})}</span></div><p><b>{b.propertyName}</b><span>{b.roomName} · {b.bookingNumber}</span></p><strong>₹{b.grossAmount.toLocaleString("en-IN")}</strong></article>)}{!filtered.length&&<div className="account-empty"><CalendarDays/><h3>No {tripTab} bookings</h3><p>Your matching stays will appear here.</p><Link href="/hotels">Plan a trip</Link></div>}</div></section>}
 {view==="wishlist"&&<section><div className="account-panel-heading"><Heart/><div><p>SAVED STAYS</p><h2>Wishlist</h2></div></div><div className="account-empty"><Heart/><h3>Your dream stays, together</h3><p>Open your wishlist to review every property you saved.</p><Link href="/wishlist">View wishlist</Link></div></section>}
 {view==="devices"&&<section><div className="account-panel-heading"><Laptop/><div><p>ACCOUNT ACCESS</p><h2>Logged-in devices</h2></div></div><div className="device-list">{sessions.map((s,i)=><article key={s.id}><Laptop/><p><b>{s.device}{i===sessions.length-1?" (Current device)":""}</b><span>Signed in {new Date(s.createdAt).toLocaleString("en-IN")}</span></p><CheckCircle2/></article>)}</div><button className="danger-outline" onClick={async()=>{await apiRequest("/api/v1/customer/sessions",token,{method:"DELETE"});logout()}}>Sign out all devices</button></section>}
 {view==="security"&&<section><div className="account-panel-heading"><KeyRound/><div><p>SECURITY</p><h2>Reset password</h2></div></div><form onSubmit={password}><label>Current password<input name="currentPassword" type="password" required/></label><label>New password<input name="newPassword" type="password" minLength={8} required/><small>Include a letter, number and special character.</small></label><button>Reset password</button></form><button className="auth-text-action" onClick={()=>router.push("/login")}>Forgot your password? Verify through WhatsApp</button></section>}
 </div></div></main>;
}
