"use client";
import Image from "next/image"; import Link from "next/link"; import { useRouter } from "next/navigation";
import { CalendarDays, CheckCircle2, CreditCard, LoaderCircle, LockKeyhole, ShieldCheck, Users } from "lucide-react";
import { FormEvent, useState } from "react";
import { apiRequest } from "@/lib/api-client"; import { CUSTOMER_TOKEN } from "@/components/customer/CustomerAuth"; import type { PublicProperty, PublicRoom } from "@/types/public-property";
declare global { interface Window { Razorpay?: new (options: Record<string, unknown>) => { open: () => void; on: (name: string, callback: (value: { error?: { description?: string } }) => void) => void } } }
type Order = { bookingId: string; bookingNumber: string; razorpayOrderId: string; keyId: string; amount: number; currency: string; propertyName: string; customer: { name: string; email: string; contact: string } };
const loadCheckout = () => new Promise<void>((resolve, reject) => { if (window.Razorpay) return resolve(); const script = document.createElement("script"); script.src = "https://checkout.razorpay.com/v1/checkout.js"; script.onload = () => resolve(); script.onerror = () => reject(new Error("Secure payment window could not be loaded")); document.head.appendChild(script); });
export function BookingCheckout({ property, room, roomId, checkIn, checkOut, guests, cover }: { property: PublicProperty; room: PublicRoom; roomId: string; checkIn: string; checkOut: string; guests: number; cover: string }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [confirmed, setConfirmed] = useState<{ id: string; number: string } | null>(null); const nights = Math.max(1, Math.round((new Date(checkOut).valueOf() - new Date(checkIn).valueOf()) / 86400000)); const rate = Number(room.baseRate || room.price || property.price || 0); const estimate = rate * nights;
  async function pay(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const token = localStorage.getItem(CUSTOMER_TOKEN) || ""; if (!token) { router.push(`/login?next=${encodeURIComponent(location.pathname + location.search)}`); return; } setBusy(true); setError(""); const form = new FormData(event.currentTarget); try { const order = (await apiRequest<{ data: Order }>("/api/v1/customer/bookings/order", token, { method: "POST", body: JSON.stringify({ propertyId: property._id, roomId, checkIn, checkOut, rooms: Number(form.get("rooms")), adults: Number(form.get("adults")), children: Number(form.get("children")), guestName: form.get("guestName"), guestEmail: form.get("guestEmail"), guestPhone: form.get("guestPhone") }) })).data; await loadCheckout(); if (!window.Razorpay) throw new Error("Razorpay Checkout is unavailable"); const instance = new window.Razorpay({ key: order.keyId, amount: order.amount, currency: order.currency, name: "Guwahati Homestay", description: `${order.propertyName} · ${nights} night stay`, order_id: order.razorpayOrderId, prefill: order.customer, theme: { color: "#af0d1d" }, modal: { ondismiss: () => setBusy(false) }, handler: async (response: Record<string, string>) => { try { await apiRequest("/api/v1/customer/bookings/verify", token, { method: "POST", body: JSON.stringify({ razorpayOrderId: response.razorpay_order_id, razorpayPaymentId: response.razorpay_payment_id, razorpaySignature: response.razorpay_signature }) }); setConfirmed({ id: order.bookingId, number: order.bookingNumber }); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } } }); instance.on("payment.failed", (response) => { setError(response.error?.description || "Payment failed. No booking was confirmed."); setBusy(false); }); instance.open(); } catch (reason) { setError((reason as Error).message); setBusy(false); } }
  if (confirmed) return <div className="booking-success"><i><CheckCircle2/></i><p>PAYMENT RECEIVED</p><h1>Your stay is confirmed.</h1><span>Booking ID <b>{confirmed.number}</b></span><p>A secure payment record has been created. The property receives its settlement after your checkout.</p><Link href="/account">View my bookings</Link></div>;
  return <main className="secure-checkout"><div className="container"><header><div><p>SECURE CHECKOUT</p><h1>Complete your reservation</h1><span><LockKeyhole/> Payment protected by Razorpay</span></div><Link href={`/hotels/${property.slug}`}>Back to property</Link></header><div className="checkout-layout"><form onSubmit={pay}><section><div className="checkout-step"><b>01</b><span><h2>Guest details</h2><p>We’ll send the confirmation to these details.</p></span></div><div className="checkout-fields"><label className="wide">Full name<input name="guestName" required minLength={2} placeholder="Guest full name"/></label><label>Email address<input name="guestEmail" type="email" required placeholder="you@example.com"/></label><label>Mobile number<input name="guestPhone" required minLength={8} placeholder="+91 98765 43210"/></label><label>Rooms<input name="rooms" type="number" min="1" max="20" defaultValue="1" required/></label><label>Adults<input name="adults" type="number" min="1" max="50" defaultValue={guests} required/></label><label>Children<input name="children" type="number" min="0" max="30" defaultValue="0" required/></label></div></section><section><div className="checkout-step"><b>02</b><span><h2>Pay securely</h2><p>Your final total is calculated securely using live property rates.</p></span></div><div className="razorpay-checkout-note"><CreditCard/><div><strong>Razorpay secure payment</strong><p>UPI, cards, netbanking and supported wallets are shown in the Razorpay window.</p></div><ShieldCheck/></div>{error && <p className="checkout-error">{error}</p>}<button className="checkout-pay" disabled={busy}>{busy ? <LoaderCircle className="spin"/> : <LockKeyhole/>}{busy ? "Preparing secure payment…" : "Continue to Razorpay"}</button></section></form><aside><div className="checkout-property">{cover && <div><Image src={cover} alt={property.displayName || property.name} fill sizes="360px"/></div>}<span><small>YOUR STAY</small><h2>{property.displayName || property.name}</h2><p>{room.name || "Room"}</p></span></div><dl><div><dt><CalendarDays/> Check-in</dt><dd>{checkIn}</dd></div><div><dt><CalendarDays/> Check-out</dt><dd>{checkOut}</dd></div><div><dt><Users/> Guests</dt><dd>{guests}</dd></div><div><dt>Nights</dt><dd>{nights}</dd></div></dl><div className="checkout-estimate"><span>Estimated room charge</span><strong>₹{estimate.toLocaleString("en-IN")}</strong><small>Taxes and extra guest charges, if applicable, are calculated before payment.</small></div></aside></div></div></main>;
}
