"use client";
/* Client-side API loading starts after the owner token is available. */
/* eslint-disable react-hooks/set-state-in-effect */
import { Banknote, CheckCircle2, ChevronRight, CircleDollarSign, Download, History, Landmark, LoaderCircle, Search, ShieldCheck, WalletCards, X } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { apiRequest } from "@/lib/api-client";

type Booking = { _id: string; bookingNumber: string; guestName: string; roomName: string; checkIn: string; checkOut: string; grossAmount: number; commissionPercent: number; commissionAmount: number; ownerNetAmount: number; status: string; settlementStatus: string; settledAt?: string };
type Transaction = { _id: string; type: string; direction: string; amount: number; description: string; status: string; createdAt: string };
type Withdrawal = { _id: string; withdrawalNumber: string; amount: number; status: string; accountMask: string; utr?: string; createdAt: string };
type Wallet = { availableBalance: number; pendingBalance: number; totalSettled: number; totalWithdrawn: number; beneficiaryName: string; accountMask: string; bankConfigured: boolean; minimumWithdrawalAmount: number };
type Payload = { wallet: Wallet; bookings: Booking[]; transactions: Transaction[]; withdrawals: Withdrawal[] };
const money = (paise: number) => `₹${(Number(paise || 0) / 100).toLocaleString("en-IN", { minimumFractionDigits: 0, maximumFractionDigits: 2 })}`;
const date = (value: string) => new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value));

export function OwnerPayments({ propertyId, propertyName, token }: { propertyId: string; propertyName: string; token: string }) {
  const [data, setData] = useState<Payload | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [search, setSearch] = useState(""); const [tab, setTab] = useState<"bookings" | "wallet" | "withdrawals">("bookings"); const [detail, setDetail] = useState<Booking | null>(null); const [modal, setModal] = useState<"bank" | "withdraw" | null>(null); const [saving, setSaving] = useState(false);
  const load = () => { setLoading(true); apiRequest<{ data: Payload }>(`/api/v1/owner/payments?propertyId=${propertyId}`, token).then((response) => setData(response.data)).catch((reason) => setError((reason as Error).message)).finally(() => setLoading(false)); };
  useEffect(load, [propertyId, token]);
  const rows = useMemo(() => (data?.bookings || []).filter((item) => `${item.bookingNumber} ${item.guestName}`.toLowerCase().includes(search.toLowerCase())), [data, search]);
  const submitBank = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget); try { await apiRequest("/api/v1/owner/payments/bank-account", token, { method: "PATCH", body: JSON.stringify({ beneficiaryName: form.get("beneficiaryName"), accountNumber: form.get("accountNumber"), ifsc: String(form.get("ifsc") || "").toUpperCase() }) }); setNotice("Withdrawal account saved securely."); setModal(null); load(); } catch (reason) { setError((reason as Error).message); } finally { setSaving(false); } };
  const withdraw = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget); try { await apiRequest("/api/v1/owner/payments/withdrawals", token, { method: "POST", body: JSON.stringify({ amount: Number(form.get("amount")) }) }); setNotice("Withdrawal sent to RazorpayX for processing."); setModal(null); load(); } catch (reason) { setError((reason as Error).message); } finally { setSaving(false); } };
  const download = () => { if (!data) return; const lines = [["Booking ID", "Guest", "Check-in", "Check-out", "Gross", "Commission", "Payable", "Settlement"], ...rows.map((x) => [x.bookingNumber, x.guestName, x.checkIn, x.checkOut, money(x.grossAmount), money(x.commissionAmount), money(x.ownerNetAmount), x.settlementStatus])]; const blob = new Blob([lines.map((x) => x.map((v) => `"${String(v).replaceAll('"', '""')}"`).join(",")).join("\n")], { type: "text/csv" }); const href = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = href; a.download = `${propertyName.replace(/\W+/g, "-").toLowerCase()}-payment-statement.csv`; a.click(); URL.revokeObjectURL(href); };
  if (loading) return <div className="payments-loading"><LoaderCircle className="spin" /> Loading wallet and settlements…</div>;
  if (!data) return <div className="owner-empty"><h2>Payments unavailable</h2><p>{error || "Unable to load payment records."}</p><button onClick={load}>Try again</button></div>;
  return <div className="owner-payments">
    {(notice || error) && <div className={`payments-alert ${error ? "error" : ""}`}>{error ? <X/> : <CheckCircle2/>}{error || notice}<button onClick={() => { setError(""); setNotice(""); }}><X/></button></div>}
    <section className="wallet-hero"><div><span><WalletCards/> OWNER WALLET</span><h2>Your earnings, ready when you are.</h2><p>Completed stays are settled automatically after platform commission.</p></div><div className="wallet-balance"><small>Available to withdraw</small><strong>{money(data.wallet.availableBalance)}</strong><button disabled={data.wallet.availableBalance < data.wallet.minimumWithdrawalAmount * 100} onClick={() => setModal(data.wallet.bankConfigured ? "withdraw" : "bank")}><Banknote/> Withdraw funds</button><em>Minimum withdrawal ₹{data.wallet.minimumWithdrawalAmount.toLocaleString("en-IN")}</em></div></section>
    <div className="payment-stats"><article><i><CircleDollarSign/></i><span>Upcoming settlement<strong>{money(data.wallet.pendingBalance)}</strong><small>Released after guest checkout</small></span></article><article><i><ShieldCheck/></i><span>Total settled<strong>{money(data.wallet.totalSettled)}</strong><small>Lifetime wallet credits</small></span></article><article><i><Landmark/></i><span>Total withdrawn<strong>{money(data.wallet.totalWithdrawn)}</strong><small>{data.wallet.bankConfigured ? `Bank ${data.wallet.accountMask}` : "Bank account not added"}</small></span><button onClick={() => setModal("bank")}>{data.wallet.bankConfigured ? "Update" : "Add bank"}</button></article></div>
    <section className="payments-workspace"><header><nav>{([["bookings", "Booking settlements"], ["wallet", "Wallet activity"], ["withdrawals", "Withdrawals"]] as const).map(([id, label]) => <button className={tab === id ? "active" : ""} onClick={() => setTab(id)} key={id}>{label}</button>)}</nav><button onClick={download}><Download/> Download statement</button></header>
      {tab === "bookings" && <><div className="payment-search"><Search/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search booking ID or guest name"/><span>{rows.length} records</span></div><div className="payment-table"><div className="payment-table-head"><span>Stay</span><span>Guest & booking</span><span>Booking amount</span><span>Commission</span><span>Payable</span><span>Status</span></div>{rows.length ? rows.map((item) => <button className="payment-row" key={item._id} onClick={() => setDetail(item)}><span><b>{date(item.checkIn)}</b><small>to {date(item.checkOut)}</small></span><span><b>{item.guestName}</b><small>{item.bookingNumber} · {item.roomName}</small></span><span>{money(item.grossAmount)}</span><span>{item.commissionPercent}% <small>{money(item.commissionAmount)}</small></span><span><b>{money(item.ownerNetAmount)}</b></span><span><em className={`payment-status ${item.settlementStatus.toLowerCase()}`}>{item.settlementStatus.replaceAll("_", " ")}</em><ChevronRight/></span></button>) : <div className="payment-empty"><History/><h3>No paid bookings yet</h3><p>Verified online bookings and their settlement status will appear here.</p></div>}</div></>}
      {tab === "wallet" && <div className="payment-feed">{data.transactions.length ? data.transactions.map((item) => <article key={item._id}><i className={item.direction.toLowerCase()}>{item.direction === "CREDIT" ? "+" : "−"}</i><span><b>{item.description}</b><small>{date(item.createdAt)} · {item.status}</small></span><strong>{item.direction === "CREDIT" ? "+" : "−"}{money(item.amount)}</strong></article>) : <div className="payment-empty"><History/><h3>No wallet activity yet</h3></div>}</div>}
      {tab === "withdrawals" && <div className="payment-feed">{data.withdrawals.length ? data.withdrawals.map((item) => <article key={item._id}><i><Landmark/></i><span><b>{item.withdrawalNumber}</b><small>{date(item.createdAt)} · {item.accountMask}{item.utr ? ` · UTR ${item.utr}` : ""}</small></span><strong>{money(item.amount)} <em className={`payment-status ${item.status.toLowerCase()}`}>{item.status}</em></strong></article>) : <div className="payment-empty"><Landmark/><h3>No withdrawals yet</h3><p>Your payout history will appear here.</p></div>}</div>}
    </section>
    {detail && <div className="payment-drawer-backdrop" onMouseDown={() => setDetail(null)}><aside className="payment-drawer" onMouseDown={(e) => e.stopPropagation()}><header><div><span>BOOKING SETTLEMENT</span><h2>{detail.bookingNumber}</h2></div><button onClick={() => setDetail(null)}><X/></button></header><section><h3>Stay details</h3><dl><div><dt>Guest</dt><dd>{detail.guestName}</dd></div><div><dt>Room</dt><dd>{detail.roomName}</dd></div><div><dt>Check-in</dt><dd>{date(detail.checkIn)}</dd></div><div><dt>Check-out</dt><dd>{date(detail.checkOut)}</dd></div></dl></section><section><h3>Payment breakup</h3><dl><div><dt>Customer paid</dt><dd>{money(detail.grossAmount)}</dd></div><div><dt>Platform commission ({detail.commissionPercent}%)</dt><dd>− {money(detail.commissionAmount)}</dd></div><div className="drawer-total"><dt>Payable to property</dt><dd>{money(detail.ownerNetAmount)}</dd></div></dl></section><div className={`drawer-settlement ${detail.settlementStatus.toLowerCase()}`}><ShieldCheck/><div><b>{detail.settlementStatus === "SETTLED" ? "Settled to your wallet" : "Protected settlement hold"}</b><p>{detail.settlementStatus === "SETTLED" ? `Released ${detail.settledAt ? date(detail.settledAt) : "after checkout"}.` : "Funds are released automatically when this stay is completed."}</p></div></div></aside></div>}
    {modal && <div className="payment-modal-backdrop" onMouseDown={() => setModal(null)}><form className="payment-modal" onSubmit={modal === "bank" ? submitBank : withdraw} onMouseDown={(e) => e.stopPropagation()}><header><i>{modal === "bank" ? <Landmark/> : <Banknote/>}</i><div><span>{modal === "bank" ? "PAYOUT ACCOUNT" : "SECURE WITHDRAWAL"}</span><h2>{modal === "bank" ? "Add your bank account" : "Withdraw from wallet"}</h2></div><button type="button" onClick={() => setModal(null)}><X/></button></header>{modal === "bank" ? <div className="payment-form"><label>Beneficiary name<input name="beneficiaryName" defaultValue={data.wallet.beneficiaryName} required placeholder="Name as per bank account"/></label><label>Account number<input name="accountNumber" inputMode="numeric" pattern="\d{6,20}" required placeholder="Bank account number"/></label><label>IFSC code<input name="ifsc" pattern="[A-Za-z]{4}0[A-Za-z0-9]{6}" required placeholder="HDFC0001234"/></label><p><ShieldCheck/> Bank details are encrypted. Withdrawals are sent through RazorpayX.</p></div> : <div className="payment-form"><div className="withdraw-available"><span>Available balance</span><strong>{money(data.wallet.availableBalance)}</strong></div><label>Withdrawal amount (₹)<input name="amount" type="number" min={data.wallet.minimumWithdrawalAmount} max={Math.floor(data.wallet.availableBalance / 100)} step="1" required placeholder={`Minimum ₹${data.wallet.minimumWithdrawalAmount}`}/></label><p><Landmark/> Funds will be sent to {data.wallet.accountMask}. Razorpay processing time may vary.</p></div>}<footer><button type="button" onClick={() => setModal(null)}>Cancel</button><button className="primary" disabled={saving}>{saving && <LoaderCircle className="spin"/>}{saving ? "Processing…" : modal === "bank" ? "Save bank account" : "Withdraw securely"}</button></footer></form></div>}
  </div>;
}
