export type SiteTheme = {
  primary?: string;
  primaryColor?: string;
  secondary?: string;
  secondaryColor?: string;
  dark?: string;
  light?: string;
  fontFamily?: string;
  headerStyle?: string;
  heroStyle?: string;
  cardStyle?: string;
  buttonStyle?: string;
  footerStyle?: string;
  layoutStyle?: string;
};

export type SiteConfig = {
  id?: string;
  _id?: string;
  name: string;
  slug: string;
  domain: string;
  domains: string[];
  city: string;
  state: string;
  country: string;
  timezone?: string;
  currency?: string;
  location?: { city?: string; state?: string; country?: string };
  logo?: string;
  favicon?: string;
  tagline?: string;
  description?: string;
  heroTitle?: string;
  heroSubtitle?: string;
  ogImage?: string;
  theme: SiteTheme;
  seo?: {
    title?: string;
    description?: string;
    keywords?: string[];
    canonicalUrl?: string;
    ogTitle?: string;
    ogDescription?: string;
    ogImage?: string;
    twitterCard?: string;
    robots?: string;
  };
  contact?: { email?: string; phone?: string; address?: string };
  social?: Record<string, string>;
  pageConfig?: Record<string, unknown>;
  status?: "active" | "inactive" | "archived";
};
