import Image from "next/image"; import Link from "next/link"; import { ArrowRight, BadgeIndianRupee, Headphones, LockKeyhole, Smartphone, Sparkles } from "lucide-react"; import { categories } from "@/data/categories"; import { destinations } from "@/data/destinations"; import { hotels } from "@/data/hotels"; import { HotelCard } from "@/components/hotel/HotelCard";
const SectionTitle=({children,href="/hotels"}:{children:React.ReactNode,href?:string})=><div className="section-title"><h2>{children}</h2><Link href={href}>View all <ArrowRight/></Link></div>;
export function HomeSections(){return <>
  <section className="container mt-24"><p className="text-center text-sm font-semibold text-slate-500">Compare and discover welcoming stays across Guwahati and Northeast India</p><div className="category-grid mt-6">{categories.map(({name,count,type,icon:Icon})=><Link key={name} href={`/hotels?destination=Guwahati&type=${type}`}><Icon/><strong>{name}</strong><span>{count}</span></Link>)}</div></section>
  <section id="offers" className="container mt-8"><div className="offer-banner"><div className="relative z-10"><span>EXCLUSIVE OFFER</span><h2>Get up to <b>50% OFF</b></h2><p>on your next booking</p><small>Book now and enjoy unforgettable deals</small><Link href="/hotels" className="btn-gold mt-5">Explore Offers</Link></div></div></section>
  <section className="container mt-10"><SectionTitle>Trending Destinations</SectionTitle><div className="horizontal-list">{destinations.map(d=><Link href={`/hotels?destination=${d.name}`} className="destination-card" key={d.name}><Image src={d.image} alt={d.name} fill className="object-cover" sizes="250px"/><div><b>{d.name}</b><span>{d.count} Properties</span></div></Link>)}</div></section>
  <section className="container mt-10"><SectionTitle>Popular Stays</SectionTitle><div className="hotel-list">{hotels.map(h=><HotelCard key={h.id} hotel={h}/>)}</div></section>
  <section className="container mt-12"><div className="benefits"><div><p className="eyebrow">THE GUWAHATI HOMESTAY PROMISE</p><h2 className="font-display text-3xl font-bold">Why Book With Guwahati Homestay?</h2></div>{[[BadgeIndianRupee,"Best Price Guarantee","Find a lower price? We’ll match it."],[Sparkles,"Local Selection","Discover welcoming stays around Guwahati."],[LockKeyhole,"Easy & Secure Booking","A fast and secure booking experience."],[Headphones,"24/7 Support","We’re here whenever you need us."]].map(([I,t,d])=>{const Icon=I as typeof BadgeIndianRupee;return <div key={t as string} className="benefit"><Icon/><p><b>{t as string}</b><span>{d as string}</span></p></div>})}</div></section>
  <section className="container mt-8"><div className="app-banner"><Smartphone className="size-20 text-red-200"/><div className="flex-1"><p className="text-gold">PLAN ON THE GO</p><h2>Book anytime, anywhere</h2><span>Keep Guwahati&apos;s best stays close at hand.</span></div><div className="flex gap-2"><button>▶ Google Play</button><button>● App Store</button></div></div></section>
  <section className="container mt-10"><SectionTitle>Top Destinations by Month</SectionTitle><div className="horizontal-list">{["August","September","October","November","December","January"].map((m,i)=><Link href={`/hotels?destination=${destinations[i].name}`} className="month-card" key={m}><div className="relative h-28"><Image src={destinations[i].image} alt={destinations[i].name} fill className="object-cover" sizes="220px"/></div><p><b>{m}</b><span>{destinations[i].name} · From ₹{[1999,1899,2199,2499,2999,2199][i].toLocaleString("en-IN")}</span></p></Link>)}</div></section>
  <section className="container mt-12 grid gap-8 rounded-3xl bg-red-50 p-7 md:grid-cols-2 md:p-10"><div><p className="eyebrow">EXPLORE MORE</p><h2 className="font-display text-3xl font-bold text-navy">Discover Stays Across Guwahati</h2><p className="mt-4 leading-7 text-slate-600">From city hotels near key landmarks to peaceful homestays, private villas and riverside retreats, Guwahati Homestay helps you find comfortable accommodation for every journey.</p></div><div><h3 className="mb-4 font-bold text-navy">Popular Searches</h3><div className="flex flex-wrap gap-2">{["Guwahati","Shillong","Kaziranga","Sohra","Tawang","Majuli","Sivasagar","Tezpur","Dibrugarh","Jorhat"].map(x=><Link className="rounded-full border border-red-100 bg-white px-4 py-2 text-sm hover:border-blue" key={x} href={`/hotels?destination=${x}`}>Stays in {x}</Link>)}</div></div></section>
  </>}
